#!/bin/bash
set -e
TARGET_DIR=$XDG_DATA_HOME
STEAM_QUAKE_DIR=$HOME/.local/steam/steamapps/common/Quake
STEAM_FLATPAK_QUAKE_DIR=$HOME/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/

if [[ -d $STEAM_QUAKE_DIR && $(find $STEAM_QUAKE_DIR -maxdepth 1 -name "id1/pak0.pak") ]]; then
    TARGET_DIR=$STEAM_QUAKE_DIR
elif [[ -d $STEAM_FLATPAK_QUAKE_DIR && $(find $STEAM_FLATPAK_QUAKE_DIR -maxdepth 1 -name "id1/pak0.pak") ]]; then
    TARGET_DIR=$STEAM_FLATPAK_QUAKE_DIR
elif [[ ! -z $XDG_DATA_HOME ]]; then
    TARGET_DIR=$XDG_DATA_HOME
else
    TARGET_DIR=$HOME/.ironwail
fi

if [[ -n $(find $TARGET_DIR -maxdepth 2 -iname "id1/pak0.pak") ]]; then
    echo "Installing LibreQuake game data to $XDG_DATA_HOME..."
    mkdir -p $TARGET_DIR/.install_tmp
    unzip -d $TARGET_DIR/.install_tmp sh.queer.librequake.zip
    mv $TARGET_DIR/.install_tmp/full/id1 $TARGET_DIR
    rm -rf $TARGET_DIR/.install_tmp sh.queer.librequake.zip
fi

if [[ -n $(find $TARGET_DIR -maxdepth 2 -iname "id1.pak0.pak") ]]; then
    echo "Installing SPRAWL 96 data to $TARGET_DIR"
    mkdir -p $TARGET_DIR/.install_tmp
    unzip -d $TARGET_DIR/.install_tmp gg.sprawl.sprawl96.zip
    mv $TARGET_DIR/.install_tmp/Sprawl $TARGET_DIR/sprawl
    rm -rf $TARGET_DIR/.install_tmp gg.sprawl.sprawl96.zip
fi
