#!/bin/bash
mkdir tmp
for game in "marathon" "marathon2" "marathon-infinity"; do
  echo "Installing $game..."
  mkdir -p /app/extra/$game
  unzip -d tmp $game-data.zip
  rm $game-data.zip
  mv "tmp/$(ls tmp)/"* /app/extra/$game
  rm -rf tmp/*
done
