name: 'Check for external updates'
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-matrix:
    name: Collect list of Flatpak manifests
    runs-on: ubuntu-latest
    outputs:
      manifests: ${{ steps.get-manifests.outputs.manifests }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - id: get-manifests
      run: |
        MANIFEST_JSON=$(find ./apps/ -maxdepth 2 -name "*.yml" | jq -R -s -c 'split("\n")' | jq 'map(select(length > 0))')
        echo manifests=$MANIFEST_JSON >> $GITHUB_OUTPUT
        echo "::group::Manifests found"
        echo $MANIFEST_JSON | jq
        echo "::endgroup::"

  flathub-data-checker-global:
    needs:
      - build-matrix
    name: ${{ matrix.manifest }}
    strategy:
      fail-fast: false
      matrix:
        manifest: ${{ fromJson(needs.build-matrix.outputs.manifests) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
      env:
        GIT_AUTHOR_NAME: Flatpak External Data Checker
        GIT_COMMITTER_NAME: Flatpak External Data Checker
        # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      with:
        args: --update --never-fork ${{ matrix.manifest }}
