name: Flatter

on:
  # Rebuild once a day
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - "*/*.yml"

jobs:
  setup:
    name: Figure out what to build and deploy
    runs-on: ubuntu-latest
    outputs:
      manifests: ${{ steps.get-manifests.outputs.manifests }}
      publish: ${{ steps.set-variables.outputs.publish }}
    steps:
    - uses: actions/checkout@v4
    - id: get-manifests
      run: |
        MANIFEST_JSON=$(find . -maxdepth 2 -name "*.yml" | jq -R -s -c 'split("\n")' | jq 'map(select(length > 0))')
        echo manifests=$MANIFEST_JSON >> $GITHUB_OUTPUT
        echo "::group::Manifests found"
        echo $MANIFEST_JSON | jq
        echo "::endgroup::"
    - id: set-variables
      run: |
        PUBLISH=false
        if [[ ${{ github.ref }} == "refs/heads/main" ]]; then PUBLISH=true; fi
        echo publish=$PUBLISH >> $GITHUB_OUTPUT

  flatter:
    needs:
      - setup
    name: ${{ matrix.arch }} ${{ matrix.manifest }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:24.08
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
        manifest: ${{ fromJson(needs.setup.outputs.manifests) }}
      fail-fast: false
      # Only one job at a time can use the shared repository cache
      max-parallel: 1

    steps:
      # Checkout a repository with Flatpak manifests
      - name: Checkout
        uses: actions/checkout@v4

      # See "Multiple Architectures" below
      - name: Setup QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      # See "GPG Signing" below
      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Generate a CNAME file on-the-fly for a configured host
      - name: Generate CNAME
        run: |
          echo "flatpak.yellowkeycard.net" > CNAME

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: ${{ matrix.manifest }}
          flatpak-builder-args: |
            --skip-if-unchanged
          flatpak-build-bundle-args: |
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
          arch: ${{ matrix.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: true
          upload-pages-includes: |
            CNAME
            default.css
            index.html

  # See "Github Pages" below
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.publish }}
    needs:
      - setup
      - flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publish repo
        id: deployment
        uses: actions/deploy-pages@v1
