name: Flatter

on:
  # Rebuild once a day
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: Publish builds
  push:
    paths:
      - "apps/*/*.yml"

jobs:
  setup:
    name: Gather manifests and publishing info
    runs-on: ubuntu-latest
    outputs:
      manifests: ${{ steps.get-manifests.outputs.manifests }}
      publish: ${{ steps.set-variables.outputs.publish }}
    steps:
    - uses: actions/checkout@v4
    - id: get-manifests
      run: |
        MANIFEST_JSON=$(find ./apps/ -maxdepth 2 -name "*.yml" | jq -R -s -c 'split("\n")' | jq 'map(select(length > 0))')
        echo manifests=$MANIFEST_JSON >> $GITHUB_OUTPUT
        echo "::group::Manifests found"
        echo $MANIFEST_JSON
        echo "::endgroup::"
    - id: set-variables
      run: |
        PUBLISH=false
        if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ inputs.publish }}" == "true" ]]; then PUBLISH=true; fi
        echo publish=$PUBLISH >> $GITHUB_OUTPUT

  flatter:
    needs:
      - setup
    name: ${{ matrix.arch }} ${{ matrix.manifest }}
    runs-on: ubuntu-latest
    outputs:
      gpgkey: ${{ steps.gpg.outputs.fingerprint }}
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:24.08
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
        manifest: ${{ fromJson(needs.setup.outputs.manifests) }}
      fail-fast: false
      # Only one job at a time can use the shared repository cache
      max-parallel: 1

    steps:
      # Checkout a repository with Flatpak manifests
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # See "Multiple Architectures" below
      - name: Setup QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      # See "GPG Signing" below
      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: ${{ matrix.manifest }}
          flatpak-build-bundle-args: |
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
          arch: ${{ matrix.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: false

      - name: Check cache
        run: ls -la /__w/flatpak-builds/flatpak-builds/cache*

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.publish }}
    needs:
      - setup
      - flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate timestamp
        id: timestamp
        run: echo timestamp=$(date +%s%N | cut -b1-13) >> $GITHUB_OUTPUT

      - name: Restore repository from cache
        uses: actions/cache/restore@v4
        with:
          path: ./_site
          key: flatter-${{ needs.flatter.outputs.gpgkey }}-${{ steps.timestamp.outputs.timestamp }}
          restore-keys: flatter-

      - name: Generate CNAME
        run: |
          echo "flatpak.yellowkeycard.net" > ./_site/CNAME

      - name: Generate index.html file
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: ./_site/index.html
          title: outie's flathub repo
          description: Various things missing from Flathub
          github-corners: https://github.com/fpiesche/flatpak-builds

      - name: Create Pages artifact
        uses: actions/upload-pages-artifact@v3

      - name: Publish repo
        id: deployment
        uses: actions/deploy-pages@v1
