name: Flatter

on:
  # Rebuild once a day
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: Publish builds
  push:
    paths:
      - "apps/*/*.yml"

jobs:
  setup:
    name: Gather manifests and publishing info
    runs-on: ubuntu-latest
    outputs:
      manifests: ${{ steps.get-manifests.outputs.manifests }}
      publish: ${{ steps.set-variables.outputs.publish }}
    steps:
    - uses: actions/checkout@v4
    - id: get-manifests
      run: |
        MANIFEST_LIST=$(find ./apps/ -maxdepth 2 -name "*.yml")
        echo manifests=$MANIFEST_LIST >> $GITHUB_OUTPUT
        echo "::group::Manifests found"
        echo $MANIFEST_LIST
        echo "::endgroup::"
    - id: set-variables
      run: |
        PUBLISH=false
        if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ inputs.publish }}" == "true" ]]; then PUBLISH=true; fi
        echo publish=$PUBLISH >> $GITHUB_OUTPUT

  flatter:
    needs:
      - setup
    name: ${{ matrix.arch }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:24.08
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
      # Only one job at a time can use the shared repository cache
      max-parallel: 1

    steps:
      # Checkout a repository with Flatpak manifests
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # See "Multiple Architectures" below
      - name: Setup QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      # See "GPG Signing" below
      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Generate a CNAME file on-the-fly for a configured host
      - name: Generate CNAME
        run: |
          echo "flatpak.yellowkeycard.net" > CNAME

      - name: Generate index.html file
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
          title: outie's flathub repo
          description: Various things missing from Flathub
          github-corners: https://github.com/fpiesche/flatpak-builds

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: ${{ needs.setup.outputs.manifests }}
          flatpak-builder-args: |
            --skip-if-unchanged
          flatpak-build-bundle-args: |
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
          arch: ${{ matrix.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: ${{ matrix.arch == 'aarch64' }}
          upload-pages-includes: |
            CNAME
            default.css
            index.html

  # See "Github Pages" below
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.publish }}
    needs:
      - setup
      - flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publish repo
        id: deployment
        uses: actions/deploy-pages@v1
