name: Flatter

on:
  # Rebuild once a day
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: Publish builds
  push:
    paths:
      - "apps/*/*.yml"

jobs:
  flatter:
    needs:
    name: ${{ matrix.arch }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:24.08
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
        # manifest: ${{ fromJson(needs.setup.outputs.manifests) }}
      fail-fast: false
      # Only one job at a time can use the shared repository cache
      max-parallel: 1

    steps:
      - name: Determine whether to publish
        run: |
            PUBLISH=false
            if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ inputs.publish }}" == "true" ]]; then PUBLISH=true; fi
            echo PUBLISH=$PUBLISH >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Generate CNAME
        run: |
          echo "flatpak.yellowkeycard.net" > CNAME

      - name: Generate index.html file
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
          title: outie's flathub repo
          description: Various things missing from Flathub
          github-corners: https://github.com/fpiesche/flatpak-builds

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: |
            apps/io.github.andrei-drexler.ironwail/io.github.andrei_drexler.ironwail.yml
            apps/io.github.elasota.aerofoil/io.github.elasota.aerofoil.yml
            apps/io.github.fpiesche.f2bgl/io.github.fpiesche.f2bgl.yml
            apps/io.github.interkarma.daggerfall-unity/io.github.interkarma.daggerfall-unity.yml
            apps/org.arx_libertatis.arxlibertatis/org.arx_libertatis.arxlibertatis.yml

          flatpak-build-bundle-args: |
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
          arch: ${{ matrix.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: ${{ matrix.arch == 'aarch64' }}
          upload-pages-includes: |
            CNAME
            default.css
            index.html

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.publish }}
    needs:
      - setup
      - flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publish repo
        id: deployment
        uses: actions/deploy-pages@v1
